### ISSUE TITLE
pattern generation

### ISSUE THREAD

**Issue by parhameftekhar** [RicardooYoung/AdverseWeatherSimulation#1]
Hi thanks for your repository. I would like to know how cloud patterns are generated?

**Comment by RicardooYoung** [comment]
Hi @parhameftekhar 
First, several patterns from the directory ***./data/patterns*** are loaded and randomly placed on a mask, with the overlapped areas being emphasized. Subsequently, the mask is transformed into a depth map, which is then used to generate fog. The shape of the generated cloud corresponds to the stacked patterns.

**Comment by parhameftekhar** [comment]
Thanks @RicardooYoung  for your explanation. I understood that part from your code but my question is how you created your patterns in your _**./data/patterns**_? I would like to have more patterns like them.

**Comment by RicardooYoung** [comment]
I collected them from the internet.

**Comment by parhameftekhar** [comment]
Thanks. @RicardooYoung
